global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'data-collector'
    static_configs:
      - targets: ['data-collector:8000']

  - job_name: 'questdb'
    static_configs:
      - targets: ['questdb:9003']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']