database:
  questdb:
    host: questdb
    port: 9009
    http_port: 9000
    connection_pool_size: 10
    max_retries: 3
    retry_backoff: 1.0
    request_timeout: 30

redis:
  host: redis
  port: 6379
  db: 0

binance:
  api_key: ""
  api_secret: ""
  testnet: true
  futures_base_url: "wss://fstream.binance.com"
  rest_base_url: "https://fapi.binance.com"

data_collection:
  symbols:
    - BTCUSDT
    - ETHUSDT
  intervals:
    - 1m
    - 3m
    - 5m
    - 15m
    - 30m
    - 1h
    - 2h
    - 4h
    - 6h
    - 8h
    - 12h
    - 1d
  buffer_size: 5000
  flush_interval: 10
  historical_days: 365

feature_engine:
  buffer_size: 2500
  flush_interval: 15
  lookback_periods: 300
  calculation_threads: 8
  feature_version: 2  # Updated for TA-Lib integration
  quality_check_interval: 600
  batch_size: 500
  indicators:
    technical:
      sma_periods: [10, 20, 50, 100, 200]
      ema_periods: [10, 20, 50, 100, 200]
      rsi_periods: [14, 21]
      atr_periods: [14, 21]
      bb_timeperiod: 20
      bb_nbdevup: 2
      bb_nbdevdn: 2
      macd_fastperiod: 12
      macd_slowperiod: 26
      macd_signalperiod: 9
      adx_timeperiod: 14
      cci_timeperiod: 20
      stoch_fastk_period: 14
      stoch_slowk_period: 3
      stoch_slowd_period: 3
      mfi_timeperiod: 14
      willr_timeperiod: 14
    custom:
      lookback_periods: [1, 5, 10, 20]
      volatility_windows: [20, 50]
    microstructure:
      lookback_windows: [5, 10, 20, 50]
  quality_thresholds:
    missing_percentage: 5.0
    outlier_percentage: 1.0
    correlation_threshold: 0.95
    zero_variance_threshold: 0.00001
  optimization:
    enable_talib_optimizations: true
    min_batch_size_for_optimization: 50

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

monitoring:
  prometheus:
    enabled: true
    port: 8000

performance:
  max_workers: 16
  batch_size: 500
  queue_size: 50000