database:
  questdb:
    host: questdb
    port: 9009
    http_port: 9000

redis:
  host: redis
  port: 6379
  db: 0

binance:
  api_key: ""
  api_secret: ""
  testnet: true
  futures_base_url: "wss://fstream.binance.com"
  rest_base_url: "https://fapi.binance.com"

data_collection:
  symbols:
    - BTCUSDT
    - ETHUSDT
  intervals:
    - 1m
    - 3m
    - 5m
    - 15m
    - 30m
    - 1h
    - 2h
    - 4h
    - 6h
    - 8h
    - 12h
    - 1d
  buffer_size: 10000
  flush_interval: 5
  historical_days: 365

feature_engine:
  buffer_size: 5000
  flush_interval: 10
  lookback_periods: 500
  calculation_threads: 8
  feature_version: 1
  quality_check_interval: 300
  indicators:
    technical:
      sma_periods: [10, 20, 50, 100, 200]
      ema_periods: [10, 20, 50, 100, 200]
      rsi_periods: [14, 21]
      atr_periods: [14, 21]
      bb_length: 20
      bb_std: 2
      macd_fast: 12
      macd_slow: 26
      macd_signal: 9
    custom:
      lookback_periods: [1, 5, 10, 20]
      volatility_windows: [20, 50]
    microstructure:
      lookback_windows: [5, 10, 20, 50]
  quality_thresholds:
    missing_percentage: 5.0
    outlier_percentage: 1.0
    correlation_threshold: 0.95
    zero_variance_threshold: 0.00001

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

monitoring:
  prometheus:
    enabled: true
    port: 8000

performance:
  max_workers: 16
  batch_size: 1000
  queue_size: 100000