database:
  questdb:
    host: questdb
    port: 9009
    http_port: 9000

redis:
  host: redis
  port: 6379
  db: 0

binance:
  api_key: ""
  api_secret: ""
  testnet: true
  futures_base_url: "wss://fstream.binance.com"
  rest_base_url: "https://fapi.binance.com"

data_collection:
  symbols:
    - BTCUSDT
    - ETHUSDT
  intervals:
    - 1m
    - 3m
    - 5m
    - 15m
    - 30m
    - 1h
    - 2h
    - 4h
    - 6h
    - 8h
    - 12h
    - 1d
  buffer_size: 10000
  flush_interval: 5

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

monitoring:
  prometheus:
    enabled: true
    port: 8000

performance:
  max_workers: 16
  batch_size: 1000
  queue_size: 100000