apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: QuestDB
    type: postgres
    access: proxy
    url: questdb:8812
    database: qdb
    user: admin
    secureJsonData:
      password: quest
    jsonData:
      sslmode: disable
      postgresVersion: 1200
      timescaledb: false